import { Injectable, inject, signal } from "@angular/core";
import { marker as _ } from "@biesbjerg/ngx-translate-extract-marker";
import { ITEM_ORGANIZATION } from "@modules/Organizations/services/service-types";
import { TranslateService } from "@ngx-translate/core";
import { CachedListsService, FilterConfig } from "@shared";

@Injectable({ providedIn: "root" })
export class LeadsFiltersService {
  #cachedLists = inject(CachedListsService);
  #translate = inject(TranslateService);

  countryId = signal<number | null>(null);
  regionId = signal<number | null>(null);
  cityId = signal<number | null>(null);

  getFilters(): FilterConfig[] {
    return [
      {
        type: "select",
        name: "status_ids",
        label: this.#translate.instant(_("stages")),
        options: this.#cachedLists.loadLists().get("dynamic_list:statuses") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
      },
      {
        type: "select",
        name: "assignees_ids",
        label: this.#translate.instant(_("assignees")),
        options: this.#cachedLists.loadLists().get("assignments:users") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
      },
      {
        type: "select",
        name: "interests_ids",
        label: this.#translate.instant(_("interests")),
        options: this.#cachedLists.loadLists().get("interests:interests") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
      },
      {
        type: "select",
        name: "tags_ids",
        label: this.#translate.instant(_("tags")),
        options: this.#cachedLists.loadLists().get("tags:tags") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
      },
      {
        type: "select",
        name: "source_ids",
        label: this.#translate.instant(_("sources")),
        options: this.#cachedLists.loadLists().get("dynamic_list:sources") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
      },
      {
        type: "switcher",
        name: "without_action_by_me",
        label: this.#translate.instant(_("untouched_by_me")),
        default: null,
        is_required: false,
        is_hidden: false,
      },
      {
        type: "switcher",
        name: "without_upcoming_action",
        label: this.#translate.instant(_("no_next_action")),
        default: null,
        is_required: false,
        is_hidden: false,
      },
      // advanced filters
      {
        type: "select",
        name: "old_status_ids",
        label: this.#translate.instant(_("from_stages")),
        options: this.#cachedLists.loadLists().get("dynamic_list:statuses") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "assignees_groups_ids",
        label: this.#translate.instant(_("assignees_groups")),
        options: this.#cachedLists.loadLists().get("assignments:groups") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "wallet_ids",
        label: this.#translate.instant(_("wallets")),
        options: this.#cachedLists.loadLists().get("dynamic_list:wallets") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "creators_ids",
        label: this.#translate.instant(_("creators")),
        options: this.#cachedLists.loadLists().get("assignments:users") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "owner_ids",
        label: this.#translate.instant(_("select_deselect_owners")),
        options: this.#cachedLists.loadLists().get("assignments:users") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "first_assignees_ids",
        label: this.#translate.instant(_("first_assignees")),
        options: this.#cachedLists.loadLists().get("assignments:users") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "leads_calls_type",
        label: this.#translate.instant(_("leads_calls_type")),
        options: this.#cachedLists.loadLists().get("leads:leads_calls_type") || [],
        default: null,
        is_required: false,
        is_multiple: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "lead_list_ids",
        label: this.#translate.instant(_("select_deselect_lead_lists")),
        options: this.#cachedLists.loadLists().get("dynamic_list:lead_lists") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "lead_classification_ids",
        label: this.#translate.instant(_("select_deselect_lead_classifications")),
        options: this.#cachedLists.loadLists().get("dynamic_list:lead_classifications") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "lead_quality_ids",
        label: this.#translate.instant(_("select_deselect_lead_qualities")),
        options: this.#cachedLists.loadLists().get("dynamic_list:lead_qualities") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "rating_ids",
        label: this.#translate.instant(_("select_deselect_ratings")),
        options: this.#cachedLists.loadLists().get("dynamic_list:ratings") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "campaign_ids",
        label: this.#translate.instant(_("campaigns")),
        options: this.#cachedLists.loadLists().get("marketing:campaigns") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "country_codes",
        label: this.#translate.instant(_("country_codes")),
        options: this.#cachedLists.loadLists().get("internationalizations:countries_codes") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "late_todos",
        label: this.#translate.instant(_("late_todos")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "todays_todos",
        label: this.#translate.instant(_("todays_todos")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "tomorrows_todos",
        label: this.#translate.instant(_("tomorrows_todos")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "upcoming_todos",
        label: this.#translate.instant(_("upcoming_todos")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "without_tickets",
        label: this.#translate.instant(_("without_tickets")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "has_international_numbers",
        label: this.#translate.instant(_("has_international_numbers")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "has_opportunities",
        label: this.#translate.instant(_("has_opportunities")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "has_no_opportunities",
        label: this.#translate.instant(_("has_no_opportunities")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "without_action",
        label: this.#translate.instant(_("untouched")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "has_scheduled_meeting",
        label: this.#translate.instant(_("has_scheduled_meeting")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },

      {
        type: "switcher",
        name: "has_done_meeting",
        label: this.#translate.instant(_("has_done_meeting")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "has_canceled_meeting",
        label: this.#translate.instant(_("has_canceled_meeting")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "with_whatsapp_msg",
        label: this.#translate.instant(_("with_whatsapp_msg")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "no_whatsapp_msg",
        label: this.#translate.instant(_("no_whatsapp_msg")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "daterange",
        name: "assignment_range",
        label: this.#translate.instant(_("select_assignment_range")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "daterange",
        name: "meeting_date_range",
        label: this.#translate.instant(_("meeting_date_range")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "daterange",
        name: "meeting_feedbacks_date_range",
        label: this.#translate.instant(_("meeting_feedbacks_date_range")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "daterange",
        name: "last_action_range",
        label: this.#translate.instant(_("select_last_action_range")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "daterange",
        name: "created_at_range",
        label: this.#translate.instant(_("creation_date_range")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "text",
        name: "title",
        label: this.#translate.instant(_("job_title")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "text",
        name: "company",
        label: this.#translate.instant(_("company")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "anded_assignees",
        label: this.#translate.instant(_("anded_assignees")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "has_more_than_one_assignee",
        label: this.#translate.instant(_("has_more_than_one_assignee")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "anded_tags",
        label: this.#translate.instant(_("anded_tags")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "anded_interests",
        label: this.#translate.instant(_("anded_interests")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "has_no_organization",
        label: this.#translate.instant(_("has_no_organization")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },

      {
        type: "daterange",
        name: "no_activity_range",
        label: this.#translate.instant(_("no_activity_range")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "account_type_ids",
        label: this.#translate.instant(_("select_deselect_account_types")),
        options: this.#cachedLists.loadLists().get("dynamic_list:account_types") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "industry_ids",
        label: this.#translate.instant(_("select_deselect_industries")),
        options: this.#cachedLists.loadLists().get("dynamic_list:industries") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "company_size_ids",
        label: this.#translate.instant(_("select_deselect_company_sizes")),
        options: this.#cachedLists.loadLists().get("dynamic_list:company_sizes") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "job_ids",
        label: this.#translate.instant(_("select_deselect_jobs")),
        options: this.#cachedLists.loadLists().get("dynamic_list:jobs") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "department_ids",
        label: this.#translate.instant(_("select_deselect_departments")),
        options: this.#cachedLists.loadLists().get("dynamic_list:departments") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "editors_ids",
        label: this.#translate.instant(_("select_deselect_editors")),
        options: this.#cachedLists.loadLists().get("assignments:users") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "country_ids",
        label: this.#translate.instant(_("select_deselect_countries")),
        options: this.#cachedLists.loadLists().get("locations:countries:ids:null") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
        onChange: (event, form) => {
          this.countryId.set(event.value);
          form.get("region_ids")?.setValue(null);
        },
      },
      {
        type: "select",
        name: "region_ids",
        label: this.#translate.instant(_("select_deselect_regions")),
        options:
          this.#cachedLists.loadLists().get(`locations:regions:ids:${this.countryId()}`) || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: !this.countryId(),
        is_advanced: true,
        onChange: (event, form) => {
          this.regionId.set(event.value);
          form.get("city_ids")?.setValue(null);
        },
      },
      {
        type: "select",
        name: "city_ids",
        label: this.#translate.instant(_("select_deselect_cities")),
        options: this.#cachedLists.loadLists().get(`locations:cities:ids:${this.regionId()}`) || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: !this.regionId(),
        is_advanced: true,
        onChange: (event, form) => {
          this.cityId.set(event.value);
          form.get("area_place_ids")?.setValue(null);
        },
      },
      {
        type: "select",
        name: "area_place_ids",
        label: this.#translate.instant(_("select_deselect_area_places")),
        options: this.#cachedLists.loadLists().get(`locations:areas:ids:${this.cityId()}`) || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: !this.cityId(),
        is_advanced: true,
      },
      {
        type: "select",
        name: "genders",
        label: this.#translate.instant(_("gender")),
        options: [
          { label: this.#translate.instant(_("male")), value: 1 },
          { label: this.#translate.instant(_("female")), value: 2 },
        ],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "has_more_than_one_meeting",
        label: this.#translate.instant(_("has_more_than_one_meeting")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "with_meeting_feedback",
        label: this.#translate.instant(_("with_meeting_feedback")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "has_more_than_one_meeting_feedback",
        label: this.#translate.instant(_("has_more_than_one_meeting_feedback")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "with_meeting_feedback_by_me",
        label: this.#translate.instant(_("with_meeting_feedback_by_me")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "without_meeting_feedback",
        label: this.#translate.instant(_("without_meeting_feedback")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "without_meeting_feedback_by_me",
        label: this.#translate.instant(_("without_meeting_feedback_by_me")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "lead_type_ids",
        label: this.#translate.instant(_("lead_type")),
        options: this.#cachedLists.loadLists().get("leads:types") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "has_international_numbers",
        label: this.#translate.instant(_("has_international_numbers")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "has_no_wallet",
        label: this.#translate.instant(_("has_no_wallet")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "has_more_than_one_source",
        label: this.#translate.instant(_("has_more_than_one_source")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "has_no_campaign",
        label: this.#translate.instant(_("has_no_campaign")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "has_campaign",
        label: this.#translate.instant(_("has_campaign")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "contact_method_ids",
        label: this.#translate.instant(_("select_deselect_contact_methods")),
        options: this.#cachedLists.loadLists().get("dynamic_list:contact_methods") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },

      {
        type: "select",
        name: "no_activities_creators_ids",
        label: this.#translate.instant(_("no_activities_by")),
        options: this.#cachedLists.loadLists().get("assignments:users") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "without_interests",
        label: this.#translate.instant(_("without_interests")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "without_tags",
        label: this.#translate.instant(_("without_tags")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "is_duplicated",
        label: this.#translate.instant(_("is_duplicated")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "is_deleted",
        label: this.#translate.instant(_("is_deleted")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "assigned_by_ids",
        label: this.#translate.instant(_("assigned_by")),
        options: this.#cachedLists.loadLists().get("assignments:users") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "activities_creators_ids",
        label: this.#translate.instant(_("activities_by")),
        options: this.#cachedLists.loadLists().get("assignments:users") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "tasks_creators_ids",
        label: this.#translate.instant(_("tasks_by")),
        options: this.#cachedLists.loadLists().get("assignments:users") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "salutation_ids",
        label: this.#translate.instant(_("select_deselect_salutations")),
        options: this.#cachedLists.loadLists().get("dynamic_list:salutations") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "suspended_creators",
        label: this.#translate.instant(_("suspended_creators")),
        options: this.#cachedLists.loadLists().get("assignments:suspended_creators") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "select",
        name: "suspended_owners",
        label: this.#translate.instant(_("suspended_owners")),
        options: this.#cachedLists.loadLists().get("assignments:suspended_creators") || [],
        default: null,
        is_required: false,
        is_multiple: true,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "daterange",
        name: "last_updated_at_range",
        label: this.#translate.instant(_("select_last_updated_at_range")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "daterange",
        name: "deleted_at_range",
        label: this.#translate.instant(_("deleted_at_range")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "autocomplete",
        name: "organization_ids",
        label: this.#translate.instant(_("organizations")),
        entity: ITEM_ORGANIZATION,
        default: null,
        is_multiple: true,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "daterange",
        name: "activties_answered_at_range",
        label: this.#translate.instant(_("activties_answered_at_range")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "daterange",
        name: "activties_no_answer_at_range",
        label: this.#translate.instant(_("activties_no_answer_at_range")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "daterange",
        name: "birthdate_range",
        label: this.#translate.instant(_("birthdate_range")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "daterange",
        name: "duplicate_added_as_new_at_range",
        label: this.#translate.instant(_("duplicate_added_as_new_at_range")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "text",
        name: "national_id",
        label: this.#translate.instant(_("national_id")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "text",
        name: "passport_number",
        label: this.#translate.instant(_("passport_number")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "text",
        name: "internal_code",
        label: this.#translate.instant(_("internal_code")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "with_referral",
        label: this.#translate.instant(_("with_referral")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
      {
        type: "switcher",
        name: "without_assignment",
        label: this.#translate.instant(_("without_assignment")),
        default: null,
        is_required: false,
        is_hidden: false,
        is_advanced: true,
      },
    ];
  }
}
