export const constants = {
  DEFAULT_LANGUAGE: "en",
  PAGE_TITLE_PREFIX: "8X CRM",
  LOGIN_SUCCESS_REDIRECT_URL: "/home",
  MIN_LENGTH_TEXT_INPUT: 8,
  MAX_LENGTH_TEXT_INPUT: 191,
  MAX_LENGTH_TEXTAREA: 16777215,
  TABLE_ROWS_LENGTH: 10,
  MAX_FILE_SIZE: 10_485_760, // 10_485_760 is in bytes and it equals to 10 mb
  DATA_LIMIT: 12,
  IDLE_TIME: 7_200_000, // 2 hours
  IDLE_LONG_TIME: 604_800_000, // 7 days
  DEFAULT_COUNTRY_ID: 110,
  DATE_FORMAT: "YYYY-MM-DD HH:mm",
  API_ENDPOINTS: {
    listBalanceSheet: "users/updateUserSMSBalanceModal",
    structuredLeadFields: "leads/lead_fields/getStructuredLeadFields?lead_type_id=1",
    getBrokers: "brokers/brokers",
    // updateCustomDataNoPermission ==> interests, tags, status_id, rating_id, lead_quality_id, lead_classification_id, lead_list_id, organization_id, birthdate, gender, color
    updateCustomDataNoPermission: "leads/leads/updateCustomDataNoPermission",
    updateCustomData: "leads/leads/updateCustomData",
    updateAssignment: "leads/leads/updateAssignment",
    deleteLeadActivity: "leads/modules/activities/delete",
    deleteLeadEvent: "leads/modules/events/delete",
    deleteLeadNote: "leads/modules/notes/delete",
    deleteLeadOpportunity: "leads/modules/opportunities/delete",
    deleteLeadTask: "leads/modules/tasks/delete",
    updateOpportunitiesData: "opportunities/opportunities/updateCustomData",
    updateActivitiesData: "activities/activities/updateCustomData",
    updateEventsData: "events/events/updateCustomData",
    updateNotesData: "notes/notes/updateCustomData",
    deleteNotes: "notes/notes/delete",
    updateTasksData: "tasks/tasks/updateCustomData",
    getSavedFilters: "saved_filters/saved_filters/getSavedFilters",
    getSavedFiltersByLink: "saved_filters/saved_filters/getSavedFiltersByLink",
    getRuleLists: "automation/rules/get-rule-lists",
    getLeadsFields: "leads/lead_type_fields/all",
    dynamicListsIndex: "dynamic_lists/dynamic_list_values/index",
  },
  icons: {
    gear: "fas fa-gear",
    gears: "fas fa-gears",
    heart: "fas fa-heart",
    tag: "fas fa-tag",
    tags: "fas fa-tags",
    info: "fas fa-circle-info",
    userGroup: "fas fa-user-group",
    bed: "fas fa-bed",
    pencil: "fas fa-pencil-alt",
    userSecret: "fas fa-user-secret",
    call: "fas fa-phone",
    callSlash: "fas fa-phone-slash",
    message: "fas fa-envelope",
    meeting: "fas fa-handshake",
    calendar: "fas fa-calendar-plus",
    calendarAlt: "fas fa-calendar-alt",
    money: "fas fa-money-bill-wave",
    check: "fas fa-check",
    note: "fa fa-sticky-note",
    mobile: "fas fa-mobile-alt",
    share: "fas fa-share-alt-square",
    list: "fas fa-list",
    robot: "fas fa-robot",
    thLarge: "fas fa-th-large",
    building: "fas fa-building",
  },
  modulesNames: {
    "Logger Module": "Logger Module", // done
    "Dynamic Lists Module": "Dynamic Lists Module", // done
    "Locations Module": "Locations Module", // done
    "Leads Module": "Leads Module", // done
    "Activities Module": "Activities Module",
    "Tasks Module": "Tasks Module", // done
    "Notes Module": "Notes Module",
    "Currencies Module": "Currencies Module",
    "Pipelines Module": "Pipelines Module", // done
    "Opportunities Module": "Opportunities Module", // done
    "Events Module": "Events Module",
    "Interests Module": "Interests Module", // done
    "Tags Module": "Tags Module", // done
    "Assignments Module": "Assignments Module",
    "Calendar Module": "Calendar Module",
    "Integrations Module": "Integrations Module",
    "Internationalizations Module": "Internationalizations Module",
    "Phones Module": "Phones Module",
    "Social Accounts Module": "Social Accounts Module",
    "Lawyers Module": "Lawyers Module",
    "Reports Module": "Reports Module", // done
    "Dashboard Module": "Dashboard Module",
    "Notifications Module": "Notifications Module",
    "Imports Module": "Imports Module",
    "Broker Inventory Module": "Broker Inventory Module", // done
    "Saved Filters Module": "Saved Filters Module",
    "Mobile Screens Module": "Mobile Screens Module",
    "Settings Module": "Settings Module", // done
    "Lead Generation Module": "Lead Generation Module",
    "Call Center Module": "Call Center Module",
    "Related Contacts Module": "Related Contacts Module",
    "Voice Notes Module": "Voice Notes Module",
    "Migrations Module": "Migrations Module",
    "Attachments Module": "Attachments Module",
    "Customer Service Module": "Customer Service Module", // done
    "SMS Module": "SMS Module",
    "Marketing Module": "Marketing Module", // done
    "Organizations Module": "Organizations Module",
    "Exports Module": "Exports Module",
    "Companies Module": "Companies Module", // done
    "About Module": "About Module", // done
    "Brokers Module": "Brokers Module",
    "HR Module": "HR Module", // done
    "Attributes Module": "Attributes Module",
    "Categories Module": "Categories Module",
    "Products Module": "Products Module",
    "Resources Module": "Resources Module", // done
    "Services Module": "Services Module",
    "User Preferences Module": "User Preferences Module",
    "Reports Scheduler Module": "Reports Scheduler Module", // done
    "Referrals Module": "Referrals Module",
    "EightX CRMs Module": "EightX CRMs Module",
    "Lookups Module": "Lookups Module", // done
    "Translations Module": "Translations Module",
    "Contracts Module": "Contracts Module",
    "Payments Module": "Payments Module",
    "Addresses Module": "Addresses Module",
    "Automation Module": "Automation Module", // done
  },
  permissions: {
    "manage-groups": "manage-groups",
    "index-groups": "index-groups",
    "create-group": "create-group",
    "view-group": "view-group",
    "update-group": "update-group",
    "delete-group": "delete-group",
    "update-group-permissions": "update-group-permissions",
    "update-group-access-scopes-groups": "update-group-access-scopes-groups",
    "manage-users": "manage-users",
    "index-users": "index-users",
    "create-user": "create-user",
    "view-user": "view-user",
    "update-user": "update-user",
    "delete-user": "delete-user",
    "update-user-permissions": "update-user-permissions",
    "manage-leads": "manage-leads",
    "index-leads": "index-leads",
    "create-lead": "create-lead",
    "view-lead": "view-lead",
    "update-lead": "update-lead",
    "delete-lead": "delete-lead",
    "manage-contacts": "manage-contacts",
    "index-contacts": "index-contacts",
    "create-contact": "create-contact",
    "view-contact": "view-contact",
    "update-contact": "update-contact",
    "delete-contact": "delete-contact",
    "manage-customers": "manage-customers",
    "index-customers": "index-customers",
    "create-customer": "create-customer",
    "view-customer": "view-customer",
    "update-customer": "update-customer",
    "delete-customer": "delete-customer",
    "manage-accounts": "manage-accounts",
    "index-accounts": "index-accounts",
    "create-account": "create-account",
    "view-account": "view-account",
    "update-account": "update-account",
    "delete-account": "delete-account",
    "manage-duplicate-leads": "manage-duplicate-leads",
    "index-duplicate-leads": "index-duplicate-leads",
    "view-duplicate-lead": "view-duplicate-lead",
    "update-duplicate-lead": "update-duplicate-lead",
    "take-action-on-duplicate-lead": "take-action-on-duplicate-lead",
    "delete-duplicate-lead": "delete-duplicate-lead",
    "manage-duplicate-contacts": "manage-duplicate-contacts",
    "index-duplicate-contacts": "index-duplicate-contacts",
    "view-duplicate-contact": "view-duplicate-contact",
    "update-duplicate-contact": "update-duplicate-contact",
    "take-action-on-duplicate-contact": "take-action-on-duplicate-contact",
    "delete-duplicate-contact": "delete-duplicate-contact",
    "manage-duplicate-customers": "manage-duplicate-customers",
    "index-duplicate-customers": "index-duplicate-customers",
    "view-duplicate-customer": "view-duplicate-customer",
    "update-duplicate-customer": "update-duplicate-customer",
    "take-action-on-duplicate-customer": "take-action-on-duplicate-customer",
    "delete-duplicate-customer": "delete-duplicate-customer",
    "manage-duplicate-accounts": "manage-duplicate-accounts",
    "index-duplicate-accounts": "index-duplicate-accounts",
    "view-duplicate-account": "view-duplicate-account",
    "update-duplicate-account": "update-duplicate-account",
    "take-action-on-duplicate-account": "take-action-on-duplicate-account",
    "delete-duplicate-account": "delete-duplicate-account",
    "manage-calendar": "manage-calendar",
    "view-calendar": "view-calendar",
    "manage-interests": "manage-interests",
    "index-interests": "index-interests",
    "create-interest": "create-interest",
    "update-interest": "update-interest",
    "delete-interest": "delete-interest",
    "manage-tags": "manage-tags",
    "index-tags": "index-tags",
    "create-tag": "create-tag",
    "update-tag": "update-tag",
    "delete-tag": "delete-tag",
    "manage-google-accounts": "manage-google-accounts",
    "index-google-accounts": "index-google-accounts",
    "add-google-account": "add-google-account",
    "delete-google-account": "delete-google-account",
    "manage-industries": "manage-industries",
    "index-industries": "index-industries",
    "create-industry": "create-industry",
    "update-industry": "update-industry",
    "delete-industry": "delete-industry",
    "manage-company-sizes": "manage-company-sizes",
    "index-company-sizes": "index-company-sizes",
    "create-company-size": "create-company-size",
    "update-company-size": "update-company-size",
    "delete-company-size": "delete-company-size",
    "manage-jobs": "manage-jobs",
    "index-jobs": "index-jobs",
    "create-job": "create-job",
    "update-job": "update-job",
    "delete-job": "delete-job",
    "manage-departments": "manage-departments",
    "index-departments": "index-departments",
    "create-department": "create-department",
    "update-department": "update-department",
    "delete-department": "delete-department",
    "manage-account-types": "manage-account-types",
    "index-account-types": "index-account-types",
    "create-account-type": "create-account-type",
    "update-account-type": "update-account-type",
    "delete-account-type": "delete-account-type",
    "manage-statuses": "manage-statuses",
    "index-statuses": "index-statuses",
    "create-status": "create-status",
    "update-status": "update-status",
    "delete-status": "delete-status",
    "manage-salutations": "manage-salutations",
    "index-salutations": "index-salutations",
    "create-salutation": "create-salutation",
    "update-salutation": "update-salutation",
    "delete-salutation": "delete-salutation",
    "manage-ratings": "manage-ratings",
    "index-ratings": "index-ratings",
    "create-rating": "create-rating",
    "update-rating": "update-rating",
    "delete-rating": "delete-rating",
    "manage-lead-sources": "manage-lead-sources",
    "index-lead-sources": "index-lead-sources",
    "create-lead-source": "create-lead-source",
    "update-lead-source": "update-lead-source",
    "delete-lead-source": "delete-lead-source",
    "manage-activities": "manage-activities",
    "view-activities": "view-activities",
    "create-activity": "create-activity",
    "update-activity": "update-activity",
    "delete-activity": "delete-activity",
    "manage-tasks": "manage-tasks",
    "view-tasks": "view-tasks",
    "create-task": "create-task",
    "update-task": "update-task",
    "delete-task": "delete-task",
    "manage-events": "manage-events",
    "create-event": "create-event",
    "update-event": "update-event",
    "delete-event": "delete-event",
    "manage-notes": "manage-notes",
    "view-notes": "view-notes",
    "create-note": "create-note",
    "update-note": "update-note",
    "delete-note": "delete-note",
    "manage-opportunities": "manage-opportunities",
    "view-opportunities": "view-opportunities",
    "create-opportunity": "create-opportunity",
    "update-opportunity": "update-opportunity",
    "delete-opportunity": "delete-opportunity",
    "manage-reports": "manage-reports",
    "view-agent-statistics-report": "view-agent-statistics-report",
    "export-agent-statistics-report": "export-agent-statistics-report",
    "view-events-report": "view-events-report",
    "export-events-report": "export-events-report",
    "export-leads": "export-leads",
    "export-contacts": "export-contacts",
    "export-customers": "export-customers",
    "export-accounts": "export-accounts",
    "export-tasks": "export-tasks",
    "view-events": "view-events",
    "export-events": "export-events",
    "manage-imports": "manage-imports",
    "import-8x-data-file": "import-8x-data-file",
    "import-facebook-sheet": "import-facebook-sheet",
    "import-leads": "import-leads",
    "import-contacts": "import-contacts",
    "import-customers": "import-customers",
    "import-accounts": "import-accounts",
    "manage-assignments": "manage-assignments",
    "assign-to-assignment-rule": "assign-to-assignment-rule",
    "assign-to-users": "assign-to-users",
    "assign-to-groups": "assign-to-groups",
    "assign-to-user-round-robin": "assign-to-user-round-robin",
    "assign-to-group-round-robin": "assign-to-group-round-robin",
    "manage-assignment-rules": "manage-assignment-rules",
    "index-assignment-rules": "index-assignment-rules",
    "create-assignment-rule": "create-assignment-rule",
    "view-assignment-rule": "view-assignment-rule",
    "update-assignment-rule": "update-assignment-rule",
    "delete-assignment-rule": "delete-assignment-rule",
    "view-lead-statistics-report": "view-lead-statistics-report",
    "export-lead-statistics-report": "export-lead-statistics-report",
    "view-lead-conversions-report": "view-lead-conversions-report",
    "export-lead-conversions-report": "export-lead-conversions-report",
    "manage-broker-inventory-developers": "manage-broker-inventory-developers",
    "index-broker-inventory-developers": "index-broker-inventory-developers",
    "create-broker-inventory-developer": "create-broker-inventory-developer",
    "update-broker-inventory-developer": "update-broker-inventory-developer",
    "delete-broker-inventory-developer": "delete-broker-inventory-developer",
    "suspend-user": "suspend-user",
    "manage-broker-inventory-area-units": "manage-broker-inventory-area-units",
    "index-broker-inventory-area-units": "index-broker-inventory-area-units",
    "create-broker-inventory-area-unit": "create-broker-inventory-area-unit",
    "update-broker-inventory-area-unit": "update-broker-inventory-area-unit",
    "delete-broker-inventory-area-unit": "delete-broker-inventory-area-unit",
    "manage-broker-inventory-bathrooms": "manage-broker-inventory-bathrooms",
    "index-broker-inventory-bathrooms": "index-broker-inventory-bathrooms",
    "create-broker-inventory-bathroom": "create-broker-inventory-bathroom",
    "update-broker-inventory-bathroom": "update-broker-inventory-bathroom",
    "delete-broker-inventory-bathroom": "delete-broker-inventory-bathroom",
    "manage-broker-inventory-bedrooms": "manage-broker-inventory-bedrooms",
    "index-broker-inventory-bedrooms": "index-broker-inventory-bedrooms",
    "create-broker-inventory-bedroom": "create-broker-inventory-bedroom",
    "update-broker-inventory-bedroom": "update-broker-inventory-bedroom",
    "delete-broker-inventory-bedroom": "delete-broker-inventory-bedroom",
    "manage-broker-inventory-finishing-types": "manage-broker-inventory-finishing-types",
    "index-broker-inventory-finishing-types": "index-broker-inventory-finishing-types",
    "create-broker-inventory-finishing-type": "create-broker-inventory-finishing-type",
    "update-broker-inventory-finishing-type": "update-broker-inventory-finishing-type",
    "delete-broker-inventory-finishing-type": "delete-broker-inventory-finishing-type",
    "manage-broker-inventory-furnishing-statuses": "manage-broker-inventory-furnishing-statuses",
    "index-broker-inventory-furnishing-statuses": "index-broker-inventory-furnishing-statuses",
    "create-broker-inventory-furnishing-status": "create-broker-inventory-furnishing-status",
    "update-broker-inventory-furnishing-status": "update-broker-inventory-furnishing-status",
    "delete-broker-inventory-furnishing-status": "delete-broker-inventory-furnishing-status",
    "manage-broker-inventory-offering-types": "manage-broker-inventory-offering-types",
    "index-broker-inventory-offering-types": "index-broker-inventory-offering-types",
    "create-broker-inventory-offering-type": "create-broker-inventory-offering-type",
    "update-broker-inventory-offering-type": "update-broker-inventory-offering-type",
    "delete-broker-inventory-offering-type": "delete-broker-inventory-offering-type",
    "manage-broker-inventory-payment-methods": "manage-broker-inventory-payment-methods",
    "index-broker-inventory-payment-methods": "index-broker-inventory-payment-methods",
    "create-broker-inventory-payment-method": "create-broker-inventory-payment-method",
    "update-broker-inventory-payment-method": "update-broker-inventory-payment-method",
    "delete-broker-inventory-payment-method": "delete-broker-inventory-payment-method",
    "manage-broker-inventory-positions": "manage-broker-inventory-positions",
    "index-broker-inventory-positions": "index-broker-inventory-positions",
    "create-broker-inventory-position": "create-broker-inventory-position",
    "update-broker-inventory-position": "update-broker-inventory-position",
    "delete-broker-inventory-position": "delete-broker-inventory-position",
    "manage-broker-inventory-views": "manage-broker-inventory-views",
    "index-broker-inventory-views": "index-broker-inventory-views",
    "create-broker-inventory-view": "create-broker-inventory-view",
    "update-broker-inventory-view": "update-broker-inventory-view",
    "delete-broker-inventory-view": "delete-broker-inventory-view",
    "manage-broker-inventory-facilities": "manage-broker-inventory-facilities",
    "index-broker-inventory-facilities": "index-broker-inventory-facilities",
    "create-broker-inventory-facility": "create-broker-inventory-facility",
    "update-broker-inventory-facility": "update-broker-inventory-facility",
    "delete-broker-inventory-facility": "delete-broker-inventory-facility",
    "manage-broker-inventory-amenities": "manage-broker-inventory-amenities",
    "index-broker-inventory-amenities": "index-broker-inventory-amenities",
    "create-broker-inventory-amenity": "create-broker-inventory-amenity",
    "update-broker-inventory-amenity": "update-broker-inventory-amenity",
    "delete-broker-inventory-amenity": "delete-broker-inventory-amenity",
    "manage-broker-inventory-purposes": "manage-broker-inventory-purposes",
    "index-broker-inventory-purposes": "index-broker-inventory-purposes",
    "create-broker-inventory-purpose": "create-broker-inventory-purpose",
    "update-broker-inventory-purpose": "update-broker-inventory-purpose",
    "delete-broker-inventory-purpose": "delete-broker-inventory-purpose",
    "manage-broker-inventory-purpose-types": "manage-broker-inventory-purpose-types",
    "index-broker-inventory-purpose-types": "index-broker-inventory-purpose-types",
    "create-broker-inventory-purpose-type": "create-broker-inventory-purpose-type",
    "update-broker-inventory-purpose-type": "update-broker-inventory-purpose-type",
    "delete-broker-inventory-purpose-type": "delete-broker-inventory-purpose-type",
    "manage-broker-inventory-projects": "manage-broker-inventory-projects",
    "index-broker-inventory-projects": "index-broker-inventory-projects",
    "create-broker-inventory-project": "create-broker-inventory-project",
    "update-broker-inventory-project": "update-broker-inventory-project",
    "delete-broker-inventory-project": "delete-broker-inventory-project",
    "manage-broker-inventory-units": "manage-broker-inventory-units",
    "index-broker-inventory-units": "index-broker-inventory-units",
    "create-broker-inventory-unit": "create-broker-inventory-unit",
    "update-broker-inventory-unit": "update-broker-inventory-unit",
    "delete-broker-inventory-unit": "delete-broker-inventory-unit",
    "view-broker-inventory-unit": "view-broker-inventory-unit",
    "export-broker-inventory-unit": "export-broker-inventory-unit",
    "assign-to-user-last-assignment-date": "assign-to-user-last-assignment-date",
    "assign-to-group-last-assignment-date": "assign-to-group-last-assignment-date",
    "delete-broker-inventory-unit-attachment": "delete-broker-inventory-unit-attachment",
    "manage-broker-inventory-publish-times": "manage-broker-inventory-publish-times",
    "index-broker-inventory-publish-times": "index-broker-inventory-publish-times",
    "create-broker-inventory-publish-time": "create-broker-inventory-publish-time",
    "update-broker-inventory-publish-time": "update-broker-inventory-publish-time",
    "delete-broker-inventory-publish-time": "delete-broker-inventory-publish-time",
    "manage-broker-inventory-rental-cases": "manage-broker-inventory-rental-cases",
    "index-broker-inventory-rental-cases": "index-broker-inventory-rental-cases",
    "create-broker-inventory-rental-case": "create-broker-inventory-rental-case",
    "update-broker-inventory-rental-case": "update-broker-inventory-rental-case",
    "delete-broker-inventory-rental-case": "delete-broker-inventory-rental-case",
    "delete-lead-attachment": "delete-lead-attachment",
    "delete-contact-attachment": "delete-contact-attachment",
    "delete-customer-attachment": "delete-customer-attachment",
    "delete-account-attachment": "delete-account-attachment",
    "bulk-assign-leads": "bulk-assign-leads",
    "bulk-assign-contacts": "bulk-assign-contacts",
    "bulk-assign-customers": "bulk-assign-customers",
    "bulk-assign-accounts": "bulk-assign-accounts",
    "manage-broker-inventory-floor-numbers": "manage-broker-inventory-floor-numbers",
    "index-broker-inventory-floor-numbers": "index-broker-inventory-floor-numbers",
    "create-broker-inventory-floor-number": "create-broker-inventory-floor-number",
    "update-broker-inventory-floor-number": "update-broker-inventory-floor-number",
    "delete-broker-inventory-floor-number": "delete-broker-inventory-floor-number",
    "manage-broker-inventory-reservations": "manage-broker-inventory-reservations",
    "index-broker-inventory-reservations": "index-broker-inventory-reservations",
    "create-broker-inventory-reservation": "create-broker-inventory-reservation",
    "update-broker-inventory-reservation": "update-broker-inventory-reservation",
    "delete-broker-inventory-reservation": "delete-broker-inventory-reservation",
    "bulk-delete-leads": "bulk-delete-leads",
    "bulk-delete-contacts": "bulk-delete-contacts",
    "bulk-delete-customers": "bulk-delete-customers",
    "bulk-delete-accounts": "bulk-delete-accounts",
    "bulk-add-interests-to-leads": "bulk-add-interests-to-leads",
    "bulk-add-interests-to-contacts": "bulk-add-interests-to-contacts",
    "bulk-add-interests-to-customers": "bulk-add-interests-to-customers",
    "bulk-add-interests-to-accounts": "bulk-add-interests-to-accounts",
    "bulk-add-tags-to-leads": "bulk-add-tags-to-leads",
    "bulk-add-tags-to-contacts": "bulk-add-tags-to-contacts",
    "bulk-add-tags-to-customers": "bulk-add-tags-to-customers",
    "bulk-add-tags-to-accounts": "bulk-add-tags-to-accounts",
    "bulk-change-leads-stage": "bulk-change-leads-stage",
    "bulk-change-contacts-stage": "bulk-change-contacts-stage",
    "bulk-change-customers-stage": "bulk-change-customers-stage",
    "bulk-change-accounts-stage": "bulk-change-accounts-stage",
    "manage-fblgi-routings": "manage-fblgi-routings",
    "index-fblgi-routings": "index-fblgi-routings",
    "view-fblgi-routings": "view-fblgi-routings",
    "create-fblgi-routing": "create-fblgi-routing",
    "update-fblgi-routing": "update-fblgi-routing",
    "delete-fblgi-routing": "delete-fblgi-routing",
    "manage-web-form-routings": "manage-web-form-routings",
    "index-web-form-routings": "index-web-form-routings",
    "view-web-form-routings": "view-web-form-routings",
    "create-web-form-routing": "create-web-form-routing",
    "update-web-form-routing": "update-web-form-routing",
    "delete-web-form-routing": "delete-web-form-routing",
    "access-fblgi-routings-technical-documentation":
      "access-fblgi-routings-technical-documentation",
    "access-web-form-routings-technical-documentation":
      "access-web-form-routings-technical-documentation",
    "manage-call-center": "manage-call-center",
    "access-call-center-calls-technical-documentation":
      "access-call-center-calls-technical-documentation",
    "bulk-re-assign-leads-duplicates": "bulk-re-assign-leads-duplicates",
    "bulk-re-assign-contacts-duplicates": "bulk-re-assign-contacts-duplicates",
    "bulk-re-assign-customers-duplicates": "bulk-re-assign-customers-duplicates",
    "bulk-re-assign-accounts-duplicates": "bulk-re-assign-accounts-duplicates",
    "bulk-delete-leads-duplicates": "bulk-delete-leads-duplicates",
    "bulk-delete-contacts-duplicates": "bulk-delete-contacts-duplicates",
    "bulk-delete-customers-duplicates": "bulk-delete-customers-duplicates",
    "bulk-delete-accounts-duplicates": "bulk-delete-accounts-duplicates",
    "bulk-merge-leads-duplicates": "bulk-merge-leads-duplicates",
    "bulk-merge-contacts-duplicates": "bulk-merge-contacts-duplicates",
    "bulk-merge-customers-duplicates": "bulk-merge-customers-duplicates",
    "bulk-merge-accounts-duplicates": "bulk-merge-accounts-duplicates",
    "bulk-add-leads-duplicates-as-new": "bulk-add-leads-duplicates-as-new",
    "bulk-add-contacts-duplicates-as-new": "bulk-add-contacts-duplicates-as-new",
    "bulk-add-customers-duplicates-as-new": "bulk-add-customers-duplicates-as-new",
    "bulk-add-accounts-duplicates-as-new": "bulk-add-accounts-duplicates-as-new",
    "manage-wallets": "manage-wallets",
    "index-wallets": "index-wallets",
    "create-wallet": "create-wallet",
    "update-wallet": "update-wallet",
    "delete-wallet": "delete-wallet",
    "bulk-change-leads-wallet": "bulk-change-leads-wallet",
    "bulk-change-contacts-wallet": "bulk-change-contacts-wallet",
    "bulk-change-customers-wallet": "bulk-change-customers-wallet",
    "bulk-change-accounts-wallet": "bulk-change-accounts-wallet",
    "manage-related-contacts": "manage-related-contacts",
    "view-related-contacts": "view-related-contacts",
    "create-related-contact": "create-related-contact",
    "update-related-contact": "update-related-contact",
    "delete-related-contact": "delete-related-contact",
    "manage-voice-notes": "manage-voice-notes",
    "view-voice-notes": "view-voice-notes",
    "create-voice-note": "create-voice-note",
    "update-voice-note": "update-voice-note",
    "delete-voice-note": "delete-voice-note",
    "access-notes-technical-documentation": "access-notes-technical-documentation",
    "manage-leads-technical-documentations": "manage-leads-technical-documentations",
    "access-search-leads-technical-documentation": "access-search-leads-technical-documentation",
    "update-lead-assignment": "update-lead-assignment",
    "update-contact-assignment": "update-contact-assignment",
    "update-customer-assignment": "update-customer-assignment",
    "update-account-assignment": "update-account-assignment",
    "view-lead-profile-view-log": "view-lead-profile-view-log",
    "view-contact-profile-view-log": "view-contact-profile-view-log",
    "view-customer-profile-view-log": "view-customer-profile-view-log",
    "view-account-profile-view-log": "view-account-profile-view-log",
    "convert-lead": "convert-lead",
    "convert-contact": "convert-contact",
    "convert-customer": "convert-customer",
    "convert-account": "convert-account",
    "access-lead-contact-details": "access-lead-contact-details",
    "access-contact-contact-details": "access-contact-contact-details",
    "access-customer-contact-details": "access-customer-contact-details",
    "access-account-contact-details": "access-account-contact-details",
    "manage-case-types": "manage-case-types",
    "view-case-types": "view-case-types",
    "create-case-type": "create-case-type",
    "update-case-type": "update-case-type",
    "delete-case-type": "delete-case-type",
    "manage-case-origins": "manage-case-origins",
    "view-case-origins": "view-case-origins",
    "create-case-origin": "create-case-origin",
    "update-case-origin": "update-case-origin",
    "delete-case-origin": "delete-case-origin",
    "manage-case-priorities": "manage-case-priorities",
    "view-case-priorities": "view-case-priorities",
    "create-case-priority": "create-case-priority",
    "update-case-priority": "update-case-priority",
    "delete-case-priority": "delete-case-priority",
    "manage-case-reasons": "manage-case-reasons",
    "view-case-reasons": "view-case-reasons",
    "create-case-reason": "create-case-reason",
    "update-case-reason": "update-case-reason",
    "delete-case-reason": "delete-case-reason",
    "manage-tickets": "manage-tickets",
    "index-tickets": "index-tickets",
    "create-ticket": "create-ticket",
    "update-ticket": "update-ticket",
    "delete-ticket": "delete-ticket",
    "bulk-change-leads-source": "bulk-change-leads-source",
    "bulk-change-contacts-source": "bulk-change-contacts-source",
    "bulk-change-customers-source": "bulk-change-customers-source",
    "bulk-change-accounts-source": "bulk-change-accounts-source",
    "bulk-change-leads-type": "bulk-change-leads-type",
    "bulk-change-contacts-type": "bulk-change-contacts-type",
    "bulk-change-customers-type": "bulk-change-customers-type",
    "bulk-change-accounts-type": "bulk-change-accounts-type",
    "bulk-change-leads-rating": "bulk-change-leads-rating",
    "bulk-change-contacts-rating": "bulk-change-contacts-rating",
    "bulk-change-customers-rating": "bulk-change-customers-rating",
    "bulk-change-accounts-rating": "bulk-change-accounts-rating",
    "view-ticket-details": "view-ticket-details",
    "export-tickets": "export-tickets",
    "delete-ticket-attachment": "delete-ticket-attachment",
    "manage-sms": "manage-sms",
    "view-sms-user-balance-sheet-details": "view-sms-user-balance-sheet-details",
    "view-sms-transfer-balance-sheet-details": "view-sms-transfer-balance-sheet-details",
    "view-sms-deliverability-details": "view-sms-deliverability-details",
    "add-sms-balance-to-user": "add-sms-balance-to-user",
    "subtract-sms-balance-from-user": "subtract-sms-balance-from-user",
    "transfer-sms-balance-to-user": "transfer-sms-balance-to-user",
    "transfer-sms-balance-from-user": "transfer-sms-balance-from-user",
    "manage-campaign-types": "manage-campaign-types",
    "index-campaign-types": "index-campaign-types",
    "create-campaign-type": "create-campaign-type",
    "update-campaign-type": "update-campaign-type",
    "delete-campaign-type": "delete-campaign-type",
    "manage-campaign-statuses": "manage-campaign-statuses",
    "index-campaign-statuses": "index-campaign-statuses",
    "create-campaign-status": "create-campaign-status",
    "update-campaign-status": "update-campaign-status",
    "delete-campaign-status": "delete-campaign-status",
    "manage-campaigns": "manage-campaigns",
    "index-campaigns": "index-campaigns",
    "create-campaign": "create-campaign",
    "update-campaign": "update-campaign",
    "delete-campaign": "delete-campaign",
    "view-campaign-details": "view-campaign-details",
    "export-campaigns": "export-campaigns",
    "delete-campaign-attachment": "delete-campaign-attachment",
    "manage-lead-campaign-statuses": "manage-lead-campaign-statuses",
    "index-lead-campaign-statuses": "index-lead-campaign-statuses",
    "create-lead-campaign-status": "create-lead-campaign-status",
    "update-lead-campaign-status": "update-lead-campaign-status",
    "delete-lead-campaign-status": "delete-lead-campaign-status",
    "export-opportunities": "export-opportunities",
    "manage-lead-campaigns": "manage-lead-campaigns",
    "index-lead-campaigns": "index-lead-campaigns",
    "attach-campaign-to-lead": "attach-campaign-to-lead",
    "detach-campaign-from-lead": "detach-campaign-from-lead",
    "change-lead-campaign-status": "change-lead-campaign-status",
    "manage-organizations": "manage-organizations",
    "index-organizations": "index-organizations",
    "create-organization": "create-organization",
    "update-organization": "update-organization",
    "delete-organization": "delete-organization",
    "view-organization-details": "view-organization-details",
    "export-organizations": "export-organizations",
    "delete-organization-attachment": "delete-organization-attachment",
    "bulk-change-leads-organization": "bulk-change-leads-organization",
    "bulk-change-contacts-organization": "bulk-change-contacts-organization",
    "bulk-change-customers-organization": "bulk-change-customers-organization",
    "bulk-change-accounts-organization": "bulk-change-accounts-organization",
    "manage-exports": "manage-exports",
    "index-exported-files": "index-exported-files",
    "view-exported-file": "view-exported-file",
    "delete-exported-file": "delete-exported-file",
    "manage-companies": "manage-companies",
    "index-companies": "index-companies",
    "create-company": "create-company",
    "update-company": "update-company",
    "delete-company": "delete-company",
    "manage-about-sections": "manage-about-sections",
    "index-about-sections": "index-about-sections",
    "create-about-section": "create-about-section",
    "update-about-section": "update-about-section",
    "delete-about-section": "delete-about-section",
    "manage-contact-methods": "manage-contact-methods",
    "index-contact-methods": "index-contact-methods",
    "create-contact-method": "create-contact-method",
    "update-contact-method": "update-contact-method",
    "delete-contact-method": "delete-contact-method",
    "manage-brokers": "manage-brokers",
    "index-brokers": "index-brokers",
    "create-broker": "create-broker",
    "update-broker": "update-broker",
    "delete-broker": "delete-broker",
    "view-broker-details": "view-broker-details",
    "export-brokers": "export-brokers",
    "delete-broker-attachment": "delete-broker-attachment",
    "manage-broker-employees": "manage-broker-employees",
    "index-broker-employees": "index-broker-employees",
    "create-broker-employee": "create-broker-employee",
    "update-broker-employee": "update-broker-employee",
    "delete-broker-employee": "delete-broker-employee",
    "view-broker-employee-details": "view-broker-employee-details",
    "export-broker-employees": "export-broker-employees",
    "delete-broker-employee-attachment": "delete-broker-employee-attachment",
    "manage-broker-inventory-blocks": "manage-broker-inventory-blocks",
    "index-broker-inventory-blocks": "index-broker-inventory-blocks",
    "create-broker-inventory-block": "create-broker-inventory-block",
    "update-broker-inventory-block": "update-broker-inventory-block",
    "delete-broker-inventory-block": "delete-broker-inventory-block",
    "manage-hr-check-ins": "manage-hr-check-ins",
    "index-hr-check-ins": "index-hr-check-ins",
    "export-hr-check-ins": "export-hr-check-ins",
    "index-hr-fake-incidents": "index-hr-fake-incidents",
    "export-hr-fake-incidents": "export-hr-fake-incidents",
    "view-lead-stages-report": "view-lead-stages-report",
    "export-lead-stages-report": "export-lead-stages-report",
    "view-lead-wallets-report": "view-lead-wallets-report",
    "export-lead-wallets-report": "export-lead-wallets-report",
    "manage-attributes": "manage-attributes",
    "view-attributes": "view-attributes",
    "create-attribute": "create-attribute",
    "update-attribute": "update-attribute",
    "delete-attribute": "delete-attribute",
    "manage-attribute-families": "manage-attribute-families",
    "view-attribute-families": "view-attribute-families",
    "create-attribute-family": "create-attribute-family",
    "update-attribue-family": "update-attribue-family",
    "delete-attribute-family": "delete-attribute-family",
    "manage-categories": "manage-categories",
    "view-categories": "view-categories",
    "create-category": "create-category",
    "update-category": "update-category",
    "delete-category": "delete-category",
    "manage-products": "manage-products",
    "view-products": "view-products",
    "create-product": "create-product",
    "update-product": "update-product",
    "delete-product": "delete-product",
    "manage-locations": "manage-locations",
    "index-locations": "index-locations",
    "create-location": "create-location",
    "update-location": "update-location",
    "delete-location": "delete-location",
    "manage-broker-inventory-config": "manage-broker-inventory-config",
    "update-broker-inventory-config": "update-broker-inventory-config",
    "hide-history-while-assigning": "hide-history-while-assigning",
    "view-trashed-broker-inventory-units": "view-trashed-broker-inventory-units",
    "restore-trashed-broker-inventory-unit": "restore-trashed-broker-inventory-unit",
    "view-lead-source": "view-lead-source",
    "view-contact-source": "view-contact-source",
    "view-customer-source": "view-customer-source",
    "view-account-source": "view-account-source",
    "view-lead-creator": "view-lead-creator",
    "view-contact-creator": "view-contact-creator",
    "view-customer-creator": "view-customer-creator",
    "view-account-creator": "view-account-creator",
    "view-lead-creation-date": "view-lead-creation-date",
    "view-contact-creation-date": "view-contact-creation-date",
    "view-customer-creation-date": "view-customer-creation-date",
    "view-account-creation-date": "view-account-creation-date",
    "view-call-recordings": "view-call-recordings",
    "bulk-delete-broker-inventory-units": "bulk-delete-broker-inventory-units",
    "manage-resources": "manage-resources",
    "index-resources": "index-resources",
    "create-resource": "create-resource",
    "update-resource": "update-resource",
    "delete-resource": "delete-resource",
    "view-resource": "view-resource",
    "manage-resource-types": "manage-resource-types",
    "index-resource-types": "index-resource-types",
    "create-resource-type": "create-resource-type",
    "update-resource-type": "update-resource-type",
    "delete-resource-type": "delete-resource-type",
    "view-resource-type": "view-resource-type",
    "manage-lead-lists": "manage-lead-lists",
    "index-lead-lists": "index-lead-lists",
    "create-lead-list": "create-lead-list",
    "update-lead-list": "update-lead-list",
    "delete-lead-list": "delete-lead-list",
    "manage-lead-classifications": "manage-lead-classifications",
    "index-lead-classifications": "index-lead-classifications",
    "create-lead-classification": "create-lead-classification",
    "update-lead-classification": "update-lead-classification",
    "delete-lead-classification": "delete-lead-classification",
    "manage-lead-qualities": "manage-lead-qualities",
    "index-lead-qualities": "index-lead-qualities",
    "create-lead-quality": "create-lead-quality",
    "update-lead-quality": "update-lead-quality",
    "delete-lead-quality": "delete-lead-quality",
    "manage-service-resource-types": "manage-service-resource-types",
    "index-service-resource-types": "index-service-resource-types",
    "create-service-resource-type": "create-service-resource-type",
    "update-service-resource-type": "update-service-resource-type",
    "delete-service-resource-type": "delete-service-resource-type",
    "manage-service-resources": "manage-service-resources",
    "index-service-resources": "index-service-resources",
    "create-service-resource": "create-service-resource",
    "update-service-resource": "update-service-resource",
    "delete-service-resource": "delete-service-resource",
    "manage-Services": "manage-Services",
    "index-services": "index-services",
    "create-service": "create-service",
    "update-service": "update-service",
    "delete-service": "delete-service",
    "update-lead-phone": "update-lead-phone",
    "update-lead-name": "update-lead-name",
    "add-phone-to-lead": "add-phone-to-lead",
    "view-trashed-leads": "view-trashed-leads",
    "restore-trashed-lead": "restore-trashed-lead",
    "bulk-restore-trashed-lead": "bulk-restore-trashed-lead",
    "update-inventory-unit-created-by-me": "update-inventory-unit-created-by-me",
    "update-inventory-unit-assigned-to-me": "update-inventory-unit-assigned-to-me",
    "export-datatables-report": "export-datatables-report",
    "export-agent-activities-report": "export-agent-activities-report",
    "export-broker-inventory-reservations": "export-broker-inventory-reservations",
    "export-broker-inventory-blocks": "export-broker-inventory-blocks",
    "manage-scheduled-reports": "manage-scheduled-reports",
    "index-scheduled-reports": "index-scheduled-reports",
    "create-scheduled-report": "create-scheduled-report",
    "update-scheduled-report": "update-scheduled-report",
    "delete-scheduled-report": "delete-scheduled-report",
    "manage-broker-inventory-unit-requests": "manage-broker-inventory-unit-requests",
    "index-broker-inventory-unit-requests": "index-broker-inventory-unit-requests",
    "create-broker-inventory-unit-request": "create-broker-inventory-unit-request",
    "update-broker-inventory-unit-request": "update-broker-inventory-unit-request",
    "delete-broker-inventory-unit-request": "delete-broker-inventory-unit-request",
    "view-broker-inventory-unit-request": "view-broker-inventory-unit-request",
    "export-broker-inventory-unit-request": "export-broker-inventory-unit-request",
    "update-broker-inventory-unit-request-config": "update-broker-inventory-unit-request-config",
    "update-broker-inventory-unit-request-matching-config":
      "edit-broker-inventory-unit-request-matching-config",
    "bulk-change-leads-cold-calls-flag": "bulk-change-leads-cold-calls-flag",
    "manage-pipelines": "manage-pipelines",
    "index-pipelines": "index-pipelines",
    "create-pipeline": "create-pipeline",
    "update-pipeline": "update-pipeline",
    "delete-pipeline": "delete-pipeline",
    "view-pipeline-details": "view-pipeline-details",
    "export-pipelines": "export-pipelines",
    "manage-pipeline-stages": "manage-pipeline-stages",
    "index-pipeline-stages": "index-pipeline-stages",
    "create-pipeline-stage": "create-pipeline-stage",
    "update-pipeline-stage": "update-pipeline-stage",
    "delete-pipeline-stage": "delete-pipeline-stage",
    "view-pipeline-stage-details": "view-pipeline-stage-details",
    "export-pipeline-stages": "export-pipeline-stages",
    "leads-data-management": "leads-data-management",
    "merge-leads": "merge-leads",
    "delete-hr-check-in": "delete-hr-check-in",
    "view-broker-inventory-holded-unit": "view-broker-inventory-holded-unit",
    "view-broker-inventory-reserved-unit": "view-broker-inventory-reserved-unit",
    "manage-referrals": "manage-referrals",
    "index-referrals": "index-referrals",
    "create-referral": "create-referral",
    "update-referral": "update-referral",
    "delete-referral": "delete-referral",
    "view-referral": "view-referral",
    "index-opportunities": "index-opportunities",
    "view-lead-journey": "view-lead-journey",
    "view-lead-assignees-logs": "view-lead-assignees-logs",
    "view-lead-logs": "view-lead-logs",
    "view-broker-inventory-on-hold-unit": "view-broker-inventory-on-hold-unit",
    "manage-automation-rules": "manage-automation-rules",
    "index-automation-rules": "index-automation-rules",
    "create-automation-rule": "create-automation-rule",
    "update-automation-rule": "update-automation-rule",
    "delete-automation-rule": "delete-automation-rule",
    "view-automation-rule": "view-automation-rule",
    "manage-contracts": "manage-contracts",
    "index-contracts": "index-contracts",
    "create-contract": "create-contract",
    "update-contract": "update-contract",
    "delete-contract": "delete-contract",
    "approve-contract": "approve-contract",
    "view-contract-details": "view-contract-details",
    "export-contracts": "export-contracts",
    "delete-contract-attachment": "delete-contract-attachment",
    "manage-payments": "manage-payments",
    "index-payments": "index-payments",
    "create-payment": "create-payment",
    "update-payment": "update-payment",
    "delete-payment": "delete-payment",
    "view-payment-details": "view-payment-details",
    "export-payments": "export-payments",
    "delete-payment-attachment": "delete-payment-attachment",
    "manage-payment-plan-templates": "manage-payment-plan-templates",
    "index-payment-plan-templates": "index-payment-plan-templates",
    "create-payment-plan-template": "create-payment-plan-template",
    "update-payment-plan-template": "update-payment-plan-template",
    "delete-payment-plan-template": "delete-payment-plan-template",
    "view-payment-plan-template-details": "view-payment-plan-template-details",
    "export-payment-plan-templates": "export-payment-plan-templates",
    "delete-payment-plan-template-attachment": "delete-payment-plan-template-attachment",
    "manage-payment-plans": "manage-payment-plans",
    "index-payment-plans": "index-payment-plans",
    "create-payment-plan": "create-payment-plan",
    "update-payment-plan": "update-payment-plan",
    "delete-payment-plan": "delete-payment-plan",
    "approve-payment-plan": "approve-payment-plan",
    "view-payment-plan-details": "view-payment-plan-details",
    "export-payment-plans": "export-payment-plans",
    "delete-payment-plan-attachment": "delete-payment-plan-attachment",
    "manage-installments": "manage-installments",
    "index-installments": "index-installments",
    "create-installment": "create-installment",
    "update-installment": "update-installment",
    "delete-installment": "delete-installment",
    "cancel-installment": "cancel-installment",
    "view-installment": "view-installment",
    "export-installments": "export-installments",
    "delete-installment-attachment": "delete-installment-attachment",
    "manage-cheques": "manage-cheques",
    "index-cheques": "index-cheques",
    "create-cheque": "create-cheque",
    "update-cheque": "update-cheque",
    "delete-cheque": "delete-cheque",
    "cancel-cheque": "cancel-cheque",
    "view-cheque": "view-cheque",
    "export-cheques": "export-cheques",
    "delete-cheque-attachment": "delete-cheque-attachment",
    "export-broker-inventory-projects": "export-broker-inventory-projects",
  },
  settingsPermissions: [
    "index-groups",
    "index-users",
    "index-interests",
    "index-tags",
    "index-industries",
    "index-company-sizes",
    "index-jobs",
    "index-departments",
    "index-account-types",
    "index-statuses",
    "index-salutations",
    "index-ratings",
    "index-lead-sources",
    "index-assignment-rules",
    "index-fblgi-routings",
    "index-web-form-routings",
    "access-fblgi-routings-technical-documentation",
    "access-web-form-routings-technical-documentation",
    "index-wallets",
    "index-campaign-types",
    "index-campaign-statuses",
    "index-lead-campaign-statuses",
    "index-companies",
    "index-contact-methods",
    "index-locations",
    "index-resource-types",
    "index-lead-lists",
    "index-lead-classifications",
    "index-lead-qualities",
    "index-scheduled-reports",
    "index-pipelines",
    "index-pipeline-stages",
    "index-automation-rules",
  ],
};
